### ISSUE TITLE
Configuration Problem

### ISSUE THREAD

**Issue by psihalive** [jncronin/mkgpt#1]
I am getting an error message while running ./configure like this:
`configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
`

**Comment by js2xxx** [comment]
I'm getting it too.

**Comment by js2xxx** [comment]
> I'm getting it too.

Now I've found the problem. It's install-sh was linked to automake-1.15 while automake's version is newer than it. Relink those and it's done.

**Comment by jncronin** [comment]
To build from git please run automake --add-missing && autoreconf prior to the build steps.  I have updated the README.
