### ISSUE TITLE
aclocal-1.15 and automake

### ISSUE THREAD

**Issue by PeterOSdev** [jncronin/mkgpt#2]
When I run "make" I get:

/bin/bash: aclocal-1.15: Command not found

But running "aclocal" works. So it is installed.

When I correct that issue manually in the Makefile (which isn't a good solution) I get another (identical) error about automake.

**Comment by jncronin** [comment]
To build from git please run automake --add-missing && autoreconf prior to the build steps.  I have updated the README.
